apiVersion: v1
kind: Service
metadata:
  name: awesome-media-discovery
spec:
  ports:
    - name: "http"
      port: 8761
      targetPort: 8761
  selector:
    app: awesome-media-discovery
  type: NodePort