zuul:
  ignored-services: "*"
  routes:
#    awesome-media-backend:
#      path: /awesome-media/**
#      url: http://localhost:8090
    awesome-media-backend: /awesome-media/**
    ribbon-test:
      path: /ribbon-test/**  

ribbon-test:
  ribbon:
    listOfServers: google.com, naver.com

eureka:
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    hostname: localhost:${server.port}
    prefer-ip-address: true
    ip-address: localhost
    non-secure-port: ${server.port}
  client:
    region: default
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:  60000